# actual track width = effective wheel base
# approximately the distance between wheels on an axis
# * can be different from nominal track width
b_actual: 0.20747221684370348

# scaling factor between nominal and actual wheel diameter
# * perfect wheels (no error): 1
err_s: 0.978

# error factor between right and left
# this could be for example due to slighly differences in wheel diameters
# * perfect wheels (no error): 1
err_d: 1.000103226023903

# initial covariances [x, y, theta]
initial_cov: [0, 0, 0,
              0, 0, 0,
              0, 0, 0]


# TODO: remove this
# should the filter use static covariances instead of incoming message covariances
use_static_cov: true

# if we use static covariances [var_right, var_left]
static_cov: [0.00000001, 0.00000001]
